### ISSUE TITLE
Upscale_typings() ussue

### ISSUE THREAD

**Issue by D-Sierra** [lcreteig/hlapro#10]
Hi,

I have tried using upscale_typings() function and found some inconsistencies. For example, if I ran the following code:

`HLA_low <- "A26 A31 B44 B57 C5 C7 DR4 DR7"
HLA_high <- upscale_typings(
       filepath = "A~C~B~DRB3-4-5~DRB1~DQB1.xlsx",
       typing = HLA_low
   )
HLA_high[1,"unphased_geno"]`

The unphased_genotype obtained is:
A*26:01g A*31:01g B*44:02g B*57:01g C*05:01g C*06:02g DQB1*03:01g DQB1*03:03g DRB1*04:01 DRB1*07:01 DRB4*01:01g DRB4*01:01g

High resolution C alleles do not match those introduced as low resolution typing. Crosschecking the result in [haplostats](https://www.haplostats.org/) this should be the most frequent unphased genotype when C alleles are not specified, but if you provide C locus data the corresponding high resolution C alleles should be C*05:01 and C*07:01. 

I tried to review the function's code and, while it is supposed to check C locus, the argument loci_input is missing "C" allele (line 115 of upscaling.R file). I tried forking the repository and adding it by myself, but the resulting function returned a tidyr error when calling it with the code above.

Any help will be welcomed.

**Comment by lcreteig** [comment]
Hi,

Thanks for inspecting the output so carefully, that's very helpful. There's 2 things going on here:

1. You were right to try to add `"C"` to the `input_loci` argument, but that was not possible due to a bug which has been fixed now. Note that HLA-C is still excluded from the default arguments; I think upscaling with low-resolution HLA-C typings is not always the best idea, as HLA-C is notoriously difficult to assign correctly based on serology.
2. Because `upscale_typings()` currently accepts only low-resolution input, it expects the old `Cw` notation for HLA-C.

If you install the latest version:

```r
remotes::install_github("lcreteig/hlapro")
```

And change your `upscale_typings()` call as follows:

```r
HLA_low <- "A26 A31 B44 B57 Cw5 Cw7 DR4 DR7"
HLA_high <- upscale_typings(filepath = "A~C~B~DRB3-4-5~DRB1~DQB1.xlsx", 
                            typing = HLA_low, 
                            loci_input = c("A", "B", "C", "DRB1", "DRB.", "DQB1"))
```

You should get the same result as HaploStats.

Please do let me know if you find any other inconsistencies; I did test the function myself but probably not as extensively as I should have.
